name: Daily Log Comment Handler

on:
  issue_comment:
    types: [created]

jobs:
  handle-daily-log:
    if: contains(github.event.comment.body, 'Daily Log:')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Process daily log comment
        run: |
          python scripts/logday.py "${{ github.event.comment.body }}" "${{ github.event.comment.user.login }}"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "${{ github.event.comment.body }}"
            git push
          fi
